on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v2
      - run: poetry self add "poetry-dynamic-versioning[plugin]"
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      - run: poetry publish --build
